import './globals.css';
import StyledJsxRegistry from './registry';
import Header from './components/Header';


export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
      <Header />
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
